### ISSUE TITLE
NoSuchMethodError: 'dagger.model.BindingGraph dagger.model.BindingGraph.create(com.google.common.graph.Network, boolean)

### ISSUE THREAD

**Issue by Jesse-Weinstein-Zonar** [arunkumar9t2/scabbard#121]
When I enable scabbard on my project (not FOSS, sadly, so I can't share it), the build fails with this ... less than clear error.

```
Caused by: java.lang.NoSuchMethodError: 'dagger.model.BindingGraph dagger.model.BindingGraph.create(com.google.common.graph.Network, boolean)'
	at dagger.model.BindingGraphProxies.bindingGraph(BindingGraphProxies.java:32)
	at dagger.internal.codegen.binding.BindingGraphConverter.convert(BindingGraphConverter.java:79)
	at dagger.internal.codegen.ComponentProcessingStep.isValid(ComponentProcessingStep.java:254)
	at dagger.internal.codegen.ComponentProcessingStep.processRootComponent(ComponentProcessingStep.java:151)
	at dagger.internal.codegen.ComponentProcessingStep.process(ComponentProcessingStep.java:131)
	at dagger.internal.codegen.ComponentProcessingStep.process(ComponentProcessingStep.java:62)
	at dagger.internal.codegen.validation.TypeCheckingProcessingStep.lambda$process$0(TypeCheckingProcessingStep.java:51)
	at com.google.common.collect.RegularImmutableMap.forEach(RegularImmutableMap.java:185)
	at dagger.internal.codegen.validation.TypeCheckingProcessingStep.process(TypeCheckingProcessingStep.java:48)
	at dagger.internal.codegen.ComponentProcessingStep.process(ComponentProcessingStep.java:124)
	at dagger.internal.codegen.ComponentProcessingStep.process(ComponentProcessingStep.java:62)
	at dagger.internal.codegen.statistics.DaggerStatisticsCollectingProcessingStep.process(DaggerStatisticsCollectingProcessingStep.java:52)
	at dagger.shaded.auto.common.BasicAnnotationProcessor.process(BasicAnnotationProcessor.java:330)
	at dagger.shaded.auto.common.BasicAnnotationProcessor.process(BasicAnnotationProcessor.java:181)
	at org.gradle.api.internal.tasks.compile.processing.DelegatingProcessor.process(DelegatingProcessor.java:62)
        ...
```

I'm still working on trying to debug it, but wanted to drop an issue here, mainly just in case anyone else comes across it, they will know. they aren't alone.

**Comment by arunkumar9t2** [comment]
Thanks for reporting, may I know the Dagger version you are using and if upgrading Dagger fixes it?

**Comment by Jesse-Weinstein-Zonar** [comment]
Whoops, forgot that -- I can confirm that I see the problem when using the most current version of Dagger2, 2.44.2.

**Comment by falqadi** [comment]
I'm seeing after upgrading my spi plugin from 2.25.4 to 2.56.2. The repo the spi plugin lives in is pretty slim, here's a PR where you can repro https://github.com/Snapchat/dagger-browser/pull/58 by just running `./gradlew build` within the plugin dir
