### ISSUE TITLE
build problem when plugin is enabled (dagger.releasablereferences @CanReleaseReferences)

### ISSUE THREAD

**Issue by mrmojtabaa** [arunkumar9t2/scabbard#71]
I have this problem when the plugin is enabled.

> A failure occurred while executing org.jetbrains.kotlin.gradle.internal.KaptExecution
   > java.lang.reflect.InvocationTargetException (no error message)

and when i build with --stacktrace . this is the details.

> Caused by: java.lang.NoClassDefFoundError: dagger/releasablereferences/ForReleasableReferences
	at dagger.internal.codegen.ForReleasableReferencesValidator.annotations(ForReleasableReferencesValidator.java:69)
	at dagger.shaded.auto.common.BasicAnnotationProcessor.getSupportedAnnotationClasses(BasicAnnotationProcessor.java:147)
	at dagger.shaded.auto.common.BasicAnnotationProcessor.getSupportedAnnotationTypes(BasicAnnotationProcessor.java:159)
	at dagger.shaded.auto.common.BasicAnnotationProcessor.getSupportedAnnotationTypes(BasicAnnotationProcessor.java:103)
	at org.jetbrains.kotlin.kapt3.base.incremental.IncrementalProcessor.getSupportedAnnotationTypes(incrementalProcessors.kt)
	at org.jetbrains.kotlin.kapt3.base.ProcessorWrapper.getSupportedAnnotationTypes(annotationProcessing.kt:187)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$ProcessorState.<init>(JavacProcessingEnvironment.java:513)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$DiscoveredProcessors$ProcessorStateIterator.next(JavacProcessingEnvironment.java:605)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:698)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1043)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1184)
	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1068)
	at org.jetbrains.kotlin.kapt3.base.AnnotationProcessingKt.doAnnotationProcessing(annotationProcessing.kt:78)
	... 27 more
Caused by: java.lang.ClassNotFoundException: dagger.releasablereferences.ForReleasableReferences
	... 42 more

i think it is related to [this issue](https://github.com/google/dagger/issues/1117).

**Comment by mrmojtabaa** [comment]
@arunkumar9t2 Any suggestions?

**Comment by arunkumar9t2** [comment]
Hello, thanks for reporting. Could you share which dagger version are you using?

**Comment by mrmojtabaa** [comment]
Wow !! I just upgraded my Dagger version to the latest version (2.32) and everything is working!
Thanks for your suggestion, and for the library you made.

**Comment by arunkumar9t2** [comment]
Great, thank you for using it!
